### ISSUE TITLE
Action environment variables are undocumented

### ISSUE THREAD

**Issue by stub42** [juju/docs#1053]
JUJU_ACTION_NAME, JUJU_ACTION_UUID and JUJU_ACTION_TAG are environment variables set in the hook environment when an action is being run.

JUJU_ACTION_UUID is useful for logging and creating an audit trail.

JUJU_ACTION_NAME is required for a script to know which action is being run, for example a Python module with several entry points for several different actions (a common way of sharing boilerplate)

I don't know what JUJU_ACTION_TAG is for.

```yaml
JUJU_ACTION_TAG: 'action-ac09cffb-3d96-4587-82ee-1105e1ca63f0',
JUJU_ACTION_NAME: 'debug',
JUJU_ACTION_UUID: 'ac09cffb-3d96-4587-82ee-1105e1ca63f0'
```
