### ISSUE TITLE
Update and possibly expand the credentials.yaml example

### ISSUE THREAD

**Issue by matthewhelmke** [juju/docs#1156]
In `credentials.md` we give a brief example of `credentials.yaml` content.

This more complete example may be more useful, or perhaps some of the info from it.

```
    credentials:
      aws:
        default-credential: peter
        default-region: us-west-2
        peter:
          auth-type: access-key
          access-key: key
          secret-key: secret
        paul:
          auth-type: access-key
          access-key: key
          secret-key: secret
      homemaas:
        peter:
          auth-type: oauth1
          maas-oauth: mass-oauth-key
      homestack:
        default-region: region-a
        peter:
          auth-type: userpass
          password: secret
          tenant-name: tenant
          username: user
      google:
        peter:
          auth-type: jsonfile
          file: path-to-json-file
      azure:
        peter:
          auth-type: userpass
          application-id: blah
          subscription-id: blah
          application-password: blah
      joyent:
        peter:
          auth-type: userpass
          sdc-user: blah
          sdc-key-id: blah
          private-key: blah (or private-key-path)
          algorithm: blah
```

**Comment by matthewhelmke** [comment]
Note that the above includes entries for MAAS and an OpenStack cloud called "homestack". These are not default options, but are available if you enter details for them by hand into a yaml file and add them.

1. Do we want to include these in our documentation?
2. If so, here are the details:

For MAAS and OpenStack clouds, it is necessary to edit a `clouds.yaml`
file and then use `juju add-cloud` to add these to Juju.
```
    clouds:
       homestack:
          type: openstack
          auth-types: [userpass, access-key]
          regions:
             london:
                endpoint: http://london/1.0
       homemaas:
          type: maas
          auth-types: [oauth1]
          endpoint: http://homemaas/MAAS
```
Assuming you a file called `personal-clouds.yaml` detailing an
OpenStack cloud called `homestack`, use this to add the cloud
to Juju: `juju add-cloud homestack personal-clouds.yaml`

Then when you `juju list-clouds`:
```
    CLOUD            TYPE        REGIONS
    aws              ec2         us-west-2, eu-west-1, ap-southeast-2 ...
    aws-china        ec2         cn-north-1
    aws-gov          ec2         us-gov-west-1
    azure            azure       eastus, southeastasia, centralindia ...
    azure-china      azure       chinaeast, chinanorth
    cloudsigma       cloudsigma  hnl, mia, sjc, wdc, zrh
    google           gce         us-east1, us-central1, europe-west1, ...
    joyent           joyent      eu-ams-1, us-sw-1, us-east-1, us-east-2 ... 
    rackspace        rackspace   ord, iad, lon, syd, hkg, dfw
    local:homestack  openstack   london
```
To bootstrap that OpenStack cloud, use: `juju bootstrap mycontroller homestack`
