### ISSUE TITLE
Instructions needed for setting up Prometheus monitoring

### ISSUE THREAD

**Issue by axw** [juju/docs#1624]
In Juju 2.1 each controller will expose Prometheus metrics over an HTTPS endpoint. The endpoint requires authorisation, so we need some docs on how to set this up. Below is something I wrote for the 2.1-beta5 release notes.

# Configuring Prometheus to scrape Juju Controller Metrics

Juju controllers now expose Prometheus metrics over an HTTPS endpoint. To feed these metrics into Prometheus, you will need to add a new scrape target to Prometheus. The metrics endpoint requires authorisation, so you will need to configure a user and password for Prometheus to use:

```
$ juju add-user prometheus
$ juju change-user-password prometheus
new password: <password>
type new password again: <password>
```

For the “prometheus” user to be able to access the metrics endpoint, you must grant the user access to the controller model:

```
$ juju grant prometheus read controller
```

Juju serves the metrics over HTTPS, with no option of degrading to HTTP. You can configure your Prometheus to skip validation, or you can store the controller’s CA certificate in a file for Prometheus to verify the server’s certificate against:

```
$ juju controller-config ca-cert > /path/to/juju-ca.crt
```

(NOTE: in 2.1-beta5 controller-config would print out the string in YAML format, which means it would include a YAML multi-line prefix. For 2.1-beta5 you will have to remove the YAML formatting. See: https://bugs.launchpad.net/juju/+bug/1661506.)

We can now add a scrape target to Prometheus. Modify prometheus.yml, adding the following scrape target:

```yaml
scrape_configs:
  job_name: juju
    metrics_path: /introspection/metrics
    scheme: https
    static_configs:
      targets: ['<controller-address>:17070']
    basic_auth:
      username: user-prometheus
      password: <password>
    tls_config:
      ca_file: /path/to/juju-ca.crt
```
