### ISSUE TITLE
Adding vsphere cloud doc can't add datacenter

### ISSUE THREAD

**Issue by AshleyLai** [juju/docs#2421]
The documentation for adding a vsphere cloud is not able to add a datacenter.
  https://jujucharms.com/docs/2.3/help-vmware

$ cat vsphere.yaml

``` 
clouds:
  vsphere_cloud:
    type: vsphere
    auth-types: [userpass]
    endpoint: 10.245.0.123
  regions:
    dc0: {}
```

$ juju add-cloud vsphere_cloud ./vsphere.yaml

```
WARNING 
property "dc0" is invalid.
```
