### ISSUE TITLE
Typo in charm tutorial

### ISSUE THREAD

**Issue by mlda065** [juju/docs#3464]
Page: https://docs.jujucharms.com/2.5/en/tutorial-k8s-charms

`metadata.yaml` says:

```
storage:
  database:
    type: filesystem
    location: /var/lib/mysql  mysql_image:
    type: oci-image
    description: Image used for mariadb pod.
```

Should say:

```
storage:
  database:
    type: filesystem
    location: /var/lib/mysql  
mysql_image:
    type: oci-image
    description: Image used for mariadb pod.
```

I tried to fix this myself. However as a new user, I cannot edit a page on discourse until I am 'trusted'. I can't get trusted until I make a few contributions. So it's a catch-22.

As far as I can tell, the only way to actually contribute is to first just flood the discourse pages with a lot of comments. Then I'll be deemed to be trustworthy because I am 'active'. *Then* I can finally submit an actual contribution.

**Comment by mlda065** [comment]
Actually, I'm not sure whether `mysql_image:` is supposed to be a child of `storage`, or a sibling.

**Comment by pmatulis** [comment]
@mlda065 Thanks for this. There must have been a copy/paste mess up. The bottom of the `metadata.yaml` file should look like this:

```
resources:
  mysql_image:
    type: oci-image
    description: "Image used for mariadb pod."
storage:
  database:
    type: filesystem
    location: /var/lib/mysql
```

I will fix this today in the 2.5 and devel branches.
