### ISSUE TITLE
http interface layer requires.py flawed

### ISSUE THREAD

**Issue by stub42** [juju/docs#911]
The example at https://jujucharms.com/docs/devel/developer-layers-interfaces#writing-the-requires-side is flawed, assuming that the providing service provides a single http relation.

```python
        services = {}
        for conv in self.conversations():
            service_name = conv.scope.split('/')[0]
            service = services.setdefault(service_name, {
                'service_name': service_name,
                'hosts': [],
            })
```

If the provider provides multiple http relations, then the services() method on the requires side will mash them together returning info about a single http relation with arbitrary ports and hostnames.

**Comment by stub42** [comment]
As an example, HAProxy attempted to use this interface and was connected to the example webservice twice, it would be undefined if it would see the admin or site ports.

Webservice:

```yaml
provides:
    admin:
        interface: http
    site:
        interface: http
```

Load Balancer (HAProxy):
```yaml
requires:
    reverseproxy:
        interface: http
provides:
    website:
        interface: http
```
